import type { NextPage } from 'next';
import Head from 'next/head';

import Hello from '@components/Hello';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Note app</h1>
      <Hello />
    </div>
  );
};

export default Home;
