import type { NextPage } from 'next';
import Head from 'next/head';

import NoteEditor from '@components/NoteEditor';

const Home: NextPage = () => {
  return (
    <div style={{ width: 500, height: 'fit-content', padding: 10, border: '1px solid red' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Note app</h1>
      <NoteEditor />
    </div>
  );
};

export default Home;
